# Basics on py and numpy 

In [1]:
import numpy as np

In [2]:
# random float in range (0,1)
np.random.rand(3)

array([0.70141421, 0.1585267 , 0.25974485])

In [3]:
# random float with std. dist
np.random.randn(3,2)

array([[-0.93110309, -0.30947491],
       [ 2.01018736, -1.32090811],
       [-0.80985007, -2.04333137]])

In [4]:
# random integer
np.random.randint(1,5,(3,2))

array([[4, 1],
       [2, 1],
       [2, 4]])

In [5]:
# generate array of ones 
np.ones((3,2))

# np.zeros() for 0s

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
# args : positional args
# argk : keyword args
def args(*args,**argk):
    print(args)
    print(argk)

In [7]:
args('hello',a = 'hi')

('hello',)
{'a': 'hi'}


In [8]:
# map basics 
list(map(int,[2.0,3.0]))

[2, 3]

In [9]:
# lambda : anmys fn
add = lambda a,b:a+b
print(2,3)

2 3


In [10]:
# filter basics 
def even(num):
    if(num%2==0):
        return True
l = [1,2,3,4,5,6]
list(filter(even,l))

[2, 4, 6]

In [11]:
# iterable : list is iterable where we can access elements one by one and evryting will be in memory when we are iterating a list
# iterator : one element in memory

lst = [1,2,3]
itr = iter(lst)

In [12]:
for i in range(len(lst)):
    print(next(itr))

1
2
3
